import numpy as np
#INFO = [Name, Age, ...]
INFO = np.array(["USER", None, None, None, None, None, None])
GREETING = np.array(['hello', 'hi', 'hey', 'sup', 'yo'])
NOUN = np.array(['name'])
PRONOUN = np.array(['I', 'you', 'it'])
VERB = np.array(['do'])
QVERB = np.array(['do', 'did', 'does', 'can', 'could', 'will', 'would', 'may',])
BEVERB = np.array(['be', 'am', 'is', 'was', 'are', 'were'])
ADJ = np.array([])
ADV = np.array([])
PREP = np.array(['about'])
CONJ = np.array([])
INTERJ = np.array([])
ARTICLE = np.array(['a', 'an', 'the'])
INTERRO = np.array(['what', 'who', 'where', 'when', 'why', 'how'])
POSS = np.array([('your','my','his','her','our','their','its'), ('my', 'your', 'his','her','our','their','its')])
OTHER = np.array([])

np.save("dataset/info", INFO)
np.save("dataset/greeting", GREETING)
np.save("dataset/noun", NOUN)
np.save("dataset/pronoun", PRONOUN)
np.save("dataset/verb", VERB)
np.save("dataset/beverb", BEVERB)
np.save("dataset/adj", ADJ)
np.save("dataset/adv", ADV)
np.save("dataset/prep", PREP)
np.save("dataset/conj", CONJ)
np.save("dataset/article", ARTICLE)
np.save("dataset/interro", INTERRO)
np.save("dataset/poss", POSS)
np.save("dataset/other", OTHER)
